cmake -G Ninja \
 -DLLVM_ENABLE_UNWIND_TABLES=False \
 -DCMAKE_BUILD_TYPE="Debug" \
 -DLLVM_USE_SPLIT_DWARF=True \
 -DLLVM_OPTIMIZED_TABLEGEN=True \
 -DLLVM_TARGETS_TO_BUILD="AArch64;RISCV;X86" \
 -DLLVM_BUILD_TESTS=True \
 ../llvm
